### ISSUE TITLE
Invalid signature of git 2.7.0 for windows

### ISSUE THREAD

**Issue by grigy** [git/git-scm.com#655] opened 2016-01-15 00:21 UTC
The signature of (2.7.0) 64-bit version of Git for Windows is not valid (reported by Windows). Just downloaded from the git-scm.com.

**Comment by 13thsymphony** [comment] 2016-01-19 18:06
I see this too, running Windows 10 build 10586. Launching the installer from File Explorer brings up the SmartScreen dialog: "Windows SmartScreen prevented an unrecognized app from starting, Running this app might put your PC at risk." This often occurs for less-popular or brand new file downloads so I'm not too surprised here.

However, Microsoft Edge gives a more ominous "The signature for this file is corrupt or invalid" message.

**Comment by yogsodoth** [comment] 2016-01-22 06:38
Same issue here.

**Comment by nelsonjchen** [comment] 2016-01-25 22:40
If I do run anyway, it says this. I guess it's signed but maybe something else is missing?

![screen shot 2016-01-25 at 2 39 21 pm](https://cloud.githubusercontent.com/assets/5363/12566978/7ab7693e-c371-11e5-8f1f-cff6e42ec445.png)

I think that "publisher" is @dscho

**Comment by dscho** [comment] 2016-01-26 09:08
Duplicate of https://github.com/git-for-windows/git/issues/592. And thanks for telling me to spend multiple hundred dollars to satisfy your needs (that's how much a SHA-2 certificate costs, thankyouverymuch).

**Comment by nelsonjchen** [comment] 2016-01-26 10:17
What? No, I'm just not sure what's happening here. I thought something might have gone wrong during the signing process. A missing flag or option or something. 

That sucks. I wasn't aware the SHA-2 thing has finally come into effect.

It is kind of funny though. Doesn't some form of this installer come with the Visual Studio installer?

**Comment by dscho** [comment] 2016-01-26 14:06
@nelsonjchen You are not sure what's happening here? I just told you. That ticket I linked to mentions that I sign the installers using my free-for-Open-Source SHA-1 certificate, and that Edge and Internet Explorer started not recognizing those signatures (due to SHA-1 being considered too weak now) on January 1st, 2016. Dunno how that is not clear from reading that ticket...

**Comment by nelsonjchen** [comment] 2016-01-26 16:43
@dscho When I posted that screenshot, I wasn't sure what was happening. I thought something went wrong during the signing process. I found this thread by Googling exactly what I saw from Edge. I didn't mean it as a request or command or anything like that to sign it with a SHA-2 certificate or anything. I was not aware that it was related to that issue. 

It was just a friendly nudge to say hello, hey, something is wrong here, are you aware? I'm sorry if my comment came off wrong.

**Comment by anilkondaveeti** [comment] 2016-01-31 15:10
I face the same issue.. Any resolution for the issue?

**Comment by 13thsymphony** [comment] 2016-02-01 01:58
Resolution, no. You can purchase a SHA-2 certificate for the maintainers.

Workaround, yes. Just ignore the warning.

**Comment by dscho** [comment] 2016-02-01 06:34
Why are you discussing this on the wrong bug tracker?

This is a Git for Windows issue: https://github.com/git-for-windows/git/issues/592

The good people at GitHub who run the git-scm.com website have no power to fix this, so this here ticket should be closed to encourage users to head over to the correct bug tracker.

**Comment by dscho** [comment] 2016-02-04 08:00
This was never a bug in git-scm.com and therefore this ticket should have been closed long ago, referring to git-for-windows/git#592 instead. Sadly, this never happened.

Maybe at least now somebody with the power can close this ticket? Git 2.7.0(2) is dual-signed and therefore addresses this.

**Closed** 2016-02-07 20:06 UTC

**Comment by dscho** [comment] 2016-02-08 19:33
@grigy could you please close https://github.com/git/git-scm.com/issues/667, too?

**Comment by grigy** [comment] 2016-02-09 03:46
I don't have rights to close it. It's opened by @jprichey.
