### ISSUE TITLE
Windows download page shows as "dangerous" in Chrome

### ISSUE THREAD

**Issue by mezz** [git/git-scm.com#1012] opened 2017-07-25 05:48 UTC
If I go to https://git-scm.com/download/win
Chrome warns me that the page is unsafe.

![chrome_2017-07-24_22-41-44](https://user-images.githubusercontent.com/916092/28557491-98cf9870-70c1-11e7-8f26-97f0b9b73213.png)
![chrome_2017-07-24_22-41-56](https://user-images.githubusercontent.com/916092/28557490-98cdcffe-70c1-11e7-88e2-0cfd604d25a7.png)

Linux, Mac, and Solaris download pages are fine.

I reported it as a potential error to google here: 
https://safebrowsing.google.com/safebrowsing/report_error/?hl=en-US

I thought I should still let you know in case there is something you need to do, or in case it's a legitimate issue.

**Comment by Jimskapt** [comment] 2017-07-25 12:23
(and I've got the same issue with Mozilla Firefox - ESR 52.2.1)

**Comment by peff** [comment] 2017-07-25 15:43
I can't reproduce now; I wonder if the safebrowsing report went through.

At any rate, the problem is not on git-scm.com itself, but in the linked Git for Windows release (which is in turn handled by GitHub's "releases" feature for that repository). So my best guess is a false positive in the safe-browsing feature that's been corrected, and there's nothing to be done at this point.

I'll close this for now, but please re-open if the problem returns.

**Closed by peff** 2017-07-25 15:43 UTC

**Comment by peff** [comment] 2017-07-25 15:45
> I'll close this for now, but please re-open if the problem returns.

And if you do see it, please relay any extra details from the "More details" button. It's not clear to me if this would have been caused by the content (a Windows executable that might trigger a false positive for malware) or if it was an SSL problem (possibly a configuration error on the part of AWS or GitHub).

**Comment by sxlijin** [comment] 2017-07-25 16:08
I was able to repro when the issue first came in, my best bet is a false
positive. Here's what "More details" showed:

[image: Inline image 2]

**Comment by peff** [comment] 2017-07-25 17:27
@sxlijin I think your image got eaten by GitHub's email-to-comment conversion.

**Comment by mezz** [comment] 2017-07-26 05:07
IIRC the "more details" button just showed the amazon aws link again, it was not very informative.
Glad the issue resolved itself.

**Comment by sxlijin** [comment] 2017-08-21 15:18
Late following up on this, but here's the image that email-to-comment ate:

![image](https://user-images.githubusercontent.com/512410/29525983-fd843d0e-8659-11e7-9e87-85ecf55988e1.png)

Like mezz said, not particularly informative, but I think it's useful to keep around for future reference nevertheless.

**Comment by peff** [comment] 2017-08-23 13:22
If this happens again, the right place to ping is probably GitHub support. This wasn't at all specific to our repository, and was a false positive in Google Safe Browsing for all GitHub-served assets (and once noticed, it was resolved by having GitHub contact Google, I believe).
