### ISSUE TITLE
Where is 2.8.1?

### ISSUE THREAD

**Issue by fatcerberus** [git/git-scm.com#730] opened 2016-04-05 00:34 UTC
Website front page says latest version is 2.8.1, but the download itself links to 2.8.0.  Was 2.8.1 pulled?

**Comment by paulschreiber** [comment] 2016-04-05 20:57
The OS X installer still links to 2.6.4.

Please link to 2.8.1:
http://downloads.sourceforge.net/project/git-osx-installer/git-2.8.1-intel-universal-mavericks.dmg

**Comment by fatcerberus** [comment] 2016-04-05 21:06
I was looking for the Windows installer, actually.

**Comment by paulschreiber** [comment] 2016-04-05 21:11
The above comment was intended for someone with commit access to the repo.

**Comment by peff** [comment] 2016-05-03 03:12
The links at https://git-scm.com/download/win now seem OK, and the OS X installer points to v2.8.1, which is the latest release there. I'm not sure what happened, but it may have just been the combined lag of the releases of Git for Windows and the OS installer (both of which are done separately by hand once upstream Git is tagged), and the lag of the site in picking up the releases (which happens via a cron job).

Since everything seems OK now, I'm going to close this, but feel free to open an issue if the site is missing released versions (right now both Win and OS X are at v2.8.1, which I think are the latest releases for each).

**Closed by peff** 2016-05-03 03:12 UTC
