### ISSUE TITLE
Generate Pro Git 2nd Edition

### ISSUE THREAD

**Issue by deisner** [git/git-scm.com#639] opened 2015-12-19 06:32 UTC
I pulled the latest master and diligently followed the README instructions. What I wind up with is an older version of git-scm.com, with only the 1st edition of the Pro Git book. How does one generate the current version of git-scm.com, with the 2nd edition of the book?

**Comment by jnavila** [comment] 2015-12-19 16:47
The repo for the second edition is at https://github.com/progit/progit2. You'll need asciidoctor to generate the book.

**Comment by deisner** [comment] 2016-02-01 16:49
I was able to generate the book with asciidoctor, but it actually worked too well -- it didn't replicate the bug I was trying to fix: #606 (and #618, #626, #637, and #640). We really need an updated set of instructions for generating the current version of git-scm.com. As it stands now, the README is two-years-old and mostly obsolete.

There hasn't been a genuine issue closure (other than self-closed issues) on this repo since October 10th. I'd like to help out, but if I can't build the current version of the site to replicate bugs, I can't fix them. 

@bry4n @schacon  :^)

**Comment by sxlijin** [comment] 2017-02-06 05:55
@deisner is this still an issue?

**Comment by deisner** [comment] 2017-02-06 19:06
@sxlijin Yes, this is still broken. When I clone the repo and follow the README instructions, I get an old version of the website. In particular, the version of the Pro Git book is version 1, not 2. Also, you can see that the Git version displayed for the download link is pretty old:

![image](https://cloud.githubusercontent.com/assets/742277/22661787/b5eac366-ec74-11e6-8081-efa8e3bad92d.png)

![image](https://cloud.githubusercontent.com/assets/742277/22661795/bbb5d678-ec74-11e6-8010-b6ac2a8b4937.png)

There are some issues with the formatting of the chapter headings, too (".1" rather than "2.1" in second screen capture, e.g.).

My read on this is that if I clone the repo, and follow the README, I should get the current  version of the website (including the Pro Git book), more or less.

**Comment by jnavila** [comment] 2017-02-07 08:13
Yeah, It's true that the second edition of the book is not dealt with in the README. Will add a line.

For now, it's just a matter of running 

```console
$ rake remote_genbook2
```

**Comment by deisner** [comment] 2017-02-07 16:38
@jnavila Thanks. That does generate the second edition of the book (and fixes the ".1" heading issue).

However, I still see the old version of the landing page (the first screenshot in my previous comment, with the "1.5.4 Latest source Release ... (2008-02-02)", e.g.)

**Comment by jnavila** [comment] 2017-02-08 08:22
I think it's related to the availability of the man pages for the different versions. So try running the scripts detailed in the README.

**Comment by deisner** [comment] 2017-02-08 16:32
I have been running the scripts, but the man page generation fails (which I probably should have mentioned -- I didn't realize this was responsible for the problem.)

As you see, it partially succeeds, but with occasional errors. Then it bails at the end:
```
$ GIT_REPO=../git/.git rake local_index
# many lines of output omitted, then:
   build: git-verify-tag
   build: git-whatchanged
   build: git-write-tree
   build: git
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-mainporcelain.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-ancillarymanipulators.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-ancillaryinterrogators.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-foreignscminterface.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-plumbingmanipulators.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-plumbinginterrogators.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-synchingrepositories.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-synchelpers.txt
fatal: Not a valid object name v1.5.3.8:Documentation/cmds-purehelpers.txt
   build: gitattributes
   build: gitignore
   build: gitk
   build: gitmodules
   build: merge-options
   build: merge-strategies
   build: pretty-formats
   build: pretty-options
   build: pull-fetch-param
   build: user-manual
v1.5.4
v1.5.4: 2008-02-01 22:10:10 -0500, 495a54bc, 2a073328
Found 149 entries
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/home/david/dev/git-scm.com/lib/tasks/local_index.rake:58:in `block (3 levels) in <top (required)>'
/home/david/dev/git-scm.com/lib/tasks/local_index.rake:20:in `each'
/home/david/dev/git-scm.com/lib/tasks/local_index.rake:20:in `block (2 levels) in <top (required)>'
/home/david/dev/git-scm.com/lib/tasks/local_index.rake:9:in `chdir'
/home/david/dev/git-scm.com/lib/tasks/local_index.rake:9:in `block in <top (required)>'
/home/david/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
/home/david/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => local_index
(See full trace by running task with --trace)
$
```

This was run against Git v2.11.1

**Comment by jnavila** [comment] 2017-02-08 20:17
Argh... I forced the run and got the same error. So, there is clearly a regression here... Mind try to bissect this ?

**Comment by jnavila** [comment] 2017-02-08 20:25
Ah, this is due to 58f4e68555fc6f75d7061bffbc7472542ffe7419. Time to have a closer look.

**Comment by sxlijin** [comment] 2017-05-18 21:05
@jnavila is this issue resolved?

**Comment by jnavila** [comment] 2017-05-18 21:08
Yep. Closing.

**Closed by jnavila** 2017-05-18 21:08 UTC
