### ISSUE TITLE
&lt; and &gt; ?

### ISSUE THREAD

**Issue by ShashankaNataraj** [git/git-scm.com#696] opened 2016-03-01 09:42 UTC
https://git-scm.com/book/en/v2/Getting-Started-Getting-Help

has 

> $ git help &lt ;verb&gt ;
$ git &lt ;verb&gt ; --help
$ man git-&lt ;verb&gt ;

**Comment by unratito** [comment] 2016-03-31 22:28
This seems to happen all along the online book:

https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History

But it's correct in the PDF version, so I guess the problem is not on the source, but on the HTML generation.

**Comment by peff** [comment] 2016-05-03 02:49
Closing as a duplicate of #753 (even though this is older, there are more details and links there). Thanks.

**Closed by peff** 2016-05-03 02:49 UTC
