### ISSUE TITLE
Swapped Checksums in Image

### ISSUE THREAD

**Issue by jakehemmerle** [git/git-scm.com#524] opened 2015-03-30 15:44 UTC
master/public/book/en/v2/book/03-git-branching/images/advance-master.png

In the image, the checksums of the latest commits for 'master' and 'testing' are swapped.

**Comment by jnavila** [comment] 2015-05-20 09:33
This has been fixed in the book 6 months ago. Sadly, the fixes don't seem to be visible on the site.

**Comment by jakehemmerle** [comment] 2015-05-20 10:21
It happens. Thanks for acknowledging!

**Comment by maxlazio** [comment] 2017-02-08 08:30
Duplicate of #472, closing this one.

**Closed by maxlazio** 2017-02-08 08:30 UTC
