### ISSUE TITLE
possible figure typo - 3.1 Git Branching

### ISSUE THREAD

**Issue by tomo111** [git/git-scm.com#479] opened 2014-12-01 13:51 UTC
Hi,
I am new to the topic of git and branching, just going through the book.

One thing I do not understand is, that in the figure:

http://git-scm.com/book/en/v2/book/03-git-branching/images/checkout-master.png
the TESTING branch points to a commit 87ab2

while on the very next one (merging):

http://git-scm.com/book/en/v2/book/03-git-branching/images/advance-master.png

the MASTER branch points to the very same commit and testing points to the other one.

Is this correct?

Thx

Tomas

**Comment by kevinventullo** [comment] 2015-01-19 20:20
No, the texts "87ab2" and "c2b9e" should be swapped in the second image.

**Comment by maxlazio** [comment] 2017-02-08 08:30
Duplicate of #472, closing this one.

**Closed by maxlazio** 2017-02-08 08:30 UTC
