### ISSUE TITLE
GIT Windows 64-bit installer download link is broken

### ISSUE THREAD

**Issue by VladimirBudovsky** [git/git-scm.com#1813] opened 2023-11-07 06:55 UTC
### Which download is failing?

GIT Windows 64-bit installer 

### Problem

It downloads the file named 255edd25-cca0-4294-909c-b46bced63e3f.
To run an installer, one must add ".exe" extension.

### Operating system and browser

Windows, Chrome and Edge

### Steps to reproduce

Try download the installer and see wrong file name

**Comment by pedrorijo91** [comment] 2023-11-07 21:23
hey @VladimirBudovsky ,

going to https://git-scm.com/download/win, and trying to download, i see normal filenames, e.g., `Git-2.42.0.2-64-bit.exe`

**Comment by VladimirBudovsky** [comment] 2023-11-08 05:38
Hi Pedro,

Thank you! Now it is ok. Maybe, some glitch… I tried it yesterday from two different computers, and it was wrong.

Vladimir

**Comment by Christophecab** [comment] 2023-11-21 09:52
Hi. Still have a bad name on downloaded file from https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe

The downloaded file is called "a93c7233-5099-4ce1-8597-efb65113b310" without extension. It seems to have the correct size.

But, it occurs only with MS Edge on my desktop. It works perfect ( correct name) when using Chrome... so weird !

**Comment by luiey-coretekno** [comment] 2023-11-30 07:45
Failed to download file as exe. Tried on chrome and edge. Still downloading as `a93c7233-5099-4ce1-8597-efb65113b310`. The other options are using PowerShell based on site download page instructions alternative. 
`winget install --id Git.Git -e --source winget` and it will successfully be installed.

If I paste URL from PowerShell downloading path directly in browser also will be saved as `a93c7233-5099-4ce1-8597-efb65113b310`.
[https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe](https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe)

**Comment by pedrorijo91** [comment] 2023-11-30 22:22
I recall having downloads with such strange names when they get stuck. if you try to download a big file, and you look at the destiny folder midway, you will usually see a file with random name, which will later be replaced by the final file with the correct filename. could this be the case?

**Comment by SalmonBasilCheese** [comment] 2023-12-07 05:05
I could opened it by just adding ' .exe ' to the last of file name. 
ex) rename to "a93c7233-5099-4ce1-8597-efb65113b310.exe", and double-click the file.

**Comment by grubbauer** [comment] 2023-12-10 12:27
Same issue, but I managed to run it. I just put .exe at the end, so it was a93c7233-5099-4ce1-8597-efb65113b310.exe.

**Comment by KyleChenpopo** [comment] 2023-12-11 01:17
@SalmonBasilCheese @grubbauer  Thank you! You both save my time! It worked.

**Comment by zarlin** [comment] 2023-12-13 12:42
Encountered the same issue. Appending the `.exe` extension works, but is not ideal.

- OS: Windows 10 x64
- Browser: Vivaldi 6.4.3160.47 (Stable channel) (64-bit)

**Comment by dscho** [comment] 2024-09-11 16:02
This looks like the same issue as https://github.com/git-for-windows/git/issues/4675 and the root cause is either with Chrome or with GitHub releases, and unfortunately nothing that Git for Windows or git-scm.com can fix.

I did vaguely remember that those problems were addressed, but I did not find any link :-(

In any case, is this still happening? If not, we can close the ticket. If it does, we need to find a better address for this report, and close this here ticket.

**Comment by zarlin** [comment] 2024-09-11 18:20
I just tested again using Vivaldi (Chromium) on Windows 10 x64, and the download works as expected (normal filename and extension).

I tested with different download links from both https://gitforwindows.org and https://git-scm.com/download/win .

So for my setup it's fixed!

**Comment by VladimirBudovsky** [comment] 2024-09-12 03:39
It worked well for me yesterday too.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dscho** [comment] 2024-09-12 07:49
Okay, good! Thank y'all for confirming.

For the record, I _vaguely_ remember that some people talked about S3 buckets where the files are stored using UUIDs as names, but that the `Content-Disposition` header was used to relate the actual file name, and that either a VPN or Chrome or _something_ misinterpreted those headers.

But as it seems to be fixed, let's close this here ticket.

**Closed by dscho** 2024-09-12 07:49 UTC
Labels: bug
