### ISSUE TITLE
[CRITICAL] Can't remove files/directory in the work directory for to older commits.

### ISSUE THREAD

**Issue by rmbeer** [git/git-scm.com#883] opened 2016-11-03 22:04 UTC
git have a serious problem for take the old commits where files and directory must not exist or exist for first time. This always have in this work space directory of ./ .

$ ls
dirA dirB
$ git init
$ git add .
$ git commit -m "p1"

[..change all..]
$ ls
dirC
$ git commit -a -m "p2"

[..change all..]
$ ls
dirC CMakeLists.txt
$ git commit -a -m "p3"

$ ls
dirC CMakeLists.txt
$ git checkout p1
$ ls
dirA dirB dirC CMakeLists.txt   <---dirA and dirB is correct, but no for dirC and CMakeList.txt
$ git checkout master
$ ls
dirC CMakeLists.txt
$ git checkout p2
$ ls
dirC CMakeLists.txt    <---dirA, dirB and dirC is correct, but no for CMakeList.txt
$ git checkout master
$ ls
dirC CMakeLists.txt

  This problem is real, also i use gitg for checking all sources files/directories of each commits and view in the gitg that all is correct. Thinking the problem have in "git checkout [hash]" command. (Yes, i use hash, not the name. I use the name in the example for the example).

**Comment by jnavila** [comment] 2016-11-04 07:32
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by jnavila** [comment] 2016-11-04 07:41
Replaying your scenario, I can see that dirC and CMakeLists.txt are not checked in when running `git commit -a`, so they remain untracked in the working directory.

**Comment by shaileshsunny** [comment] 2016-11-06 06:50
I think there are some issues with the functions

**Comment by jnavila** [comment] 2016-11-06 10:24
There is no issues with git itself. Reading the manual pages for "git add":

>        -a, --all      Tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected.

So dirC and CMakeLists.txt are not automatically added to your commit.

**Comment by rmbeer** [comment] 2016-11-06 18:01
no, nothing have a untracked. why i view with "git status". All files is send.

Also anybody read this in the first comment: "This problem is real, also i use gitg for checking all sources files/directories of each commits and view in the gitg that all is correct." . i say that all file is logged. "git checkout" for go to old commits in the same branch not work. Repeat, have problem for files that created in the first time.

**Comment by jnavila** [comment] 2016-11-06 18:16
So the scenario you wrote in the issue description is not the one that you are having problems with. I tested your scenario and I found that it wasn't showing anything wrong.

Secondly, I can assure you that git checkout to previous commit works correctly for me. So something is not done correctly on your part, and I cannot decypher it from your test case.

**Comment by jnavila** [comment] 2016-11-06 18:17
Can you create a repo, push it to github and give directions to reproduce the "bug"? On another point, what is your version of git?

**Comment by rmbeer** [comment] 2016-11-07 20:01
yes, i also not have a problem if i reproduce by a testcase. Only happens in my real proyect, unknown why. Also i can't put nothing about of my real proyect, sorry. I'm out of ideas of where to look or how to report the problem....

**Comment by maxlazio** [comment] 2017-02-07 19:43
Heya, 

thanks for raising an issue! Since this issue tracker is dedicated to git-scm.com website you might have more success with your issue if you raise your question in one of community channels listed at https://git-scm.com/community .

**Closed by maxlazio** 2017-02-07 19:43 UTC
