### ISSUE TITLE
merge-base documentation incorrectly rendered

### ISSUE THREAD

**Issue by rgom** [git/git-scm.com#779] opened 2016-06-07 13:27 UTC
Hi all,
discussion about merge base on https://git-scm.com/docs/git-merge-base is incorrect.
`
     o---o---o---B
    /
---o---1---o---o---o---A
`
"

the merge base between A and B is 1.
"

The description doesn't match the graph. The graph is probably a culprit, linking branch B to "o" instead of "1".
This file is ok: https://github.com/git/git/blob/master/Documentation/git-merge-base.txt
The same with local "git help merge-base" output.

Other graphs look fine.

Thanks,
Robert

**Comment by peff** [comment] 2016-06-07 19:13
Closing as a duplicate of #680. The issue is mismatched tab sizes between asciidoctor and the git documentation.

**Closed by peff** 2016-06-07 19:13 UTC
