### ISSUE TITLE
Broken link to a ProGit book page presented via search

### ISSUE THREAD

**Issue by sivaraam** [git/git-scm.com#1642] opened 2021-10-24 18:45 UTC
Searching for keyword presented a result which turned out to be a broken link.

### URL for broken page
https://git-scm.com/book/en/Appendix-A:-Git-in-Other-Environments-Git-in-IntelliJ-/-PyCharm-/-WebStorm-/-PhpStorm-/-RubyMine

### Problem
When I searched for "intelliJ" in the search bar, I got the result for "Appendix A: Git in Other Environments - Git in IntelliJ / PyCharm / WebStorm / PhpStorm / RubyMine" section of the ProGit book. When I clicked on it though, it resulted in a 404 for the following URL:

```
https://git-scm.com/book/en/Appendix-A:-Git-in-Other-Environments-Git-in-IntelliJ-/-PyCharm-/-WebStorm-/-PhpStorm-/-RubyMine
```

I guess the culprit is that the URL should be encoded but it isn't. When I try to access the section by going to https://git-scm.com/book/en/v2 and clicking on the link to the same section, it works fine.

### Operating system and browser
Firefox on Windows 10

### Steps to reproduce
1. Open https://git-scm.com
2. Search for "intellij"
3. Click on the result under the "Book" category.

**Comment by C-Lion** [comment] 2021-10-30 19:38
I think I understand the issue but it is not clear from your information which of the above needs to be corrected or  what exactly you want changed. 
Seems like a lot of code just to display a URL. 
So just confirming this is not just a  "correct the URL on the page issue"? 
I have basic Ruby skills & will try the correct rake command to see if I can get this set up locally.

**Comment by peff** [comment] 2021-11-02 15:26
> So just confirming this is not just a "correct the URL on the page issue"?

Right. The problem is that the URL is not found in this repository at all. It is in content which is imported from another repository (the book code). Hence the complexity. A cron job pulls in updated book content into the sql database nightly, and then we run a search index on that content, putting the result into the elasticsearch database. And then incoming search requests query the elasticsearch database. So if we are going to add a layer of quoting to the URL, it needs to happen either when we index the content and stick it into elasticsearch, or when we pull it out and return it to the browser.

**Comment by Nikolai48Nick** [comment] 2023-11-27 00:40
> Searching for keyword presented a result which turned out to be a broken link.
> 
> ### URL for broken page
> https://git-scm.com/book/en/Appendix-A:-Git-in-Other-Environments-Git-in-IntelliJ-/-PyCharm-/-WebStorm-/-PhpStorm-/-RubyMine
> 
> ### Problem
> When I searched for "intelliJ" in the search bar, I got the result for "Appendix A: Git in Other Environments - Git in IntelliJ / PyCharm / WebStorm / PhpStorm / RubyMine" section of the ProGit book. When I clicked on it though, it resulted in a 404 for the following URL:
> 
> ```
> https://git-scm.com/book/en/Appendix-A:-Git-in-Other-Environments-Git-in-IntelliJ-/-PyCharm-/-WebStorm-/-PhpStorm-/-RubyMine
> ```
> 
> I guess the culprit is that the URL should be encoded but it isn't. When I try to access the section by going to https://git-scm.com/book/en/v2 and clicking on the link to the same section, it works fine.
> 
> ### Operating system and browser
> Firefox on Windows 10
> 
> ### Steps to reproduce
> 1. Open https://git-scm.com
> 2. Search for "intellij"
> 3. Click on the result under the "Book" category.
>

**Comment by dscho** [comment] 2024-09-24 22:15
After #1804 was merged, [searching for `phpstorm`](https://git-scm.com/search/results?search=phpstorm&language=en) will result in a working link. So I think we can close this here ticket?

**Closed** 2024-10-25 07:04 UTC
Labels: Hacktoberfest
