### ISSUE TITLE
styling: nesting of definitions lists isn't clear

### ISSUE THREAD

**Issue by jasonkarns** [git/git-scm.com#812] opened 2016-07-25 14:37 UTC
A stylistic design nit: nested definition lists don't clearly stand out that they are nested.

Example: https://git-scm.com/docs/merge-strategies The mass of options to the `recursive` strategy look like they are "top-level" (ie, merge strategies of their own, rather than options to the `recursive` strategy)

I kept referring back to the page over the course of about 10 minutes after numerous attempts of using the options as strategies before it finally became clear that they were nested. Even now knowing they are nested, it's still rather difficult to see where the nesting ends. Perhaps just increasing the indent a bit more would be sufficient. But I'll leave the design solution to the designers.

**Comment by peff** [comment] 2016-07-25 15:33
I agree it's a little hard to notice the nesting. They _are_ indented, but it's such a small amount that it's easy to miss in a long block.

I'm not sure how easy this will be to fix. The content itself is pulled directly from git's Asciidoc manpages, and the formatting is done by Asciidoctor. So I'm not sure if the fix should go into Asciidoctor, or if we could just tweak some css on our side (I guess we could _always_ tweak some css as a workaround, but I'm not sure if we do much styling of Asciidoctor generated classes at this point).

**Comment by sxlijin** [comment] 2017-02-06 05:34
Duplicate of #701

**Closed** 2017-02-06 13:19 UTC
