### ISSUE TITLE
I think the image is wrongly label

### ISSUE THREAD

**Issue by idhamhafidz** [git/git-scm.com#578] opened 2015-08-29 03:11 UTC
Hi,

I was checking on branching topic. I think it is wrongly label. May cause confusion to others.

87ab2 should be the other way around.

it should be c2b9e

Love everyone who contribute to this work. Thanks everyone and may Allah reward you.

![screenshot from 2015-08-29 11 05 43](https://cloud.githubusercontent.com/assets/1255203/9560287/6747b76c-4e3e-11e5-9c61-26147984d888.png)

**Comment by sxlijin** [comment] 2017-02-07 17:25
Huh, surprised this hasn't been fixed after so long, or that no one else caught it...

@peff this should be fixed. Interestingly enough, the [.pdf (p88)](https://progit2.s3.amazonaws.com/en/2016-03-22-f3531/progit-en.1084.pdf) does *not* have this problem even though the [page](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#_switching_branches) does.

**Comment by peff** [comment] 2017-02-07 21:56
Hmm, this should have been fixed long ago by https://github.com/progit/progit2/issues/136. And as @jnavila re-imported the book images recently, I'd think we would be up to date. Weird...

**Comment by sxlijin** [comment] 2017-02-07 23:39
Duplicate of #524, one of the two should get closed.

**Comment by maxlazio** [comment] 2017-02-08 08:32
Since #472 is the original issue reporting this, I'll close this one in favour of #472.

**Closed by maxlazio** 2017-02-08 08:32 UTC
