### ISSUE TITLE
Do not immediately start a download without user interaction

### ISSUE THREAD

**Issue by crucialfelix** [git/git-scm.com#518] opened 2015-03-18 11:48 UTC
I am on a Mac. I googled to get some information about installing git on windows and your site comes up.

When I click on the search result I am brought to:

http://git-scm.com/download/win

which immediately begins downloading a windows exe.  

Even if I was on windows, its an anti-pattern to download software before the visitor has a chance to evaluate who you are, if you can be trusted and to find out what is being offered.

**Comment by harriha** [comment] 2015-09-16 18:14
Seconded - I'd propose disabling this auto-download behavior as well. The download page contains alternative downloads also, thus auto-download will result in unnecessary downloads in many cases (which is quite annoying).

**Comment by sxlijin** [comment] 2017-02-07 23:42
This is generally a browser-level feature if I'm not mistaken. I'm not the biggest fan, but I do also believe it's better UX - although then again, considering the userbase, it may very well make more sense to disable automatic downloads. @peff thoughts?

**Comment by sxlijin** [comment] 2017-02-08 00:19
Duplicate of #373.

**Comment by crucialfelix** [comment] 2017-02-08 16:42
You've already fixed this. The link now points to "downloads":
https://git-scm.com/downloads

which is perfectly clear.

Previously I had it automatically download just by visiting the site
(following a google link).

**Closed** 2017-02-08 17:30 UTC
