### ISSUE TITLE
Broken link on ch4.1

### ISSUE THREAD

**Issue by smarts** [git/git-scm.com#967] opened 2017-02-20 09:27 UTC
From https://git-scm.com/book/ch4-1.html
> Read [Credential Storage](https://git-scm.com/book/ch00/_credential_caching) to see how to set up secure HTTP password caching on your system.

The link doesn't work.

**Comment by peff** [comment] 2017-02-20 21:02
This is the same bug as #786.

The root cause is that the `ch4-1` URLs aren't _supposed_ to be used at all. They're historical. Do you happen to know where you followed that link from?

**Comment by peff** [comment] 2017-02-20 21:02
Closing as duplicate.

**Closed by peff** 2017-02-20 21:02 UTC

**Comment by smarts** [comment] 2017-02-22 16:33
@peff I think I got there from Google, but I'm not sure. I was looking for info on the `git://` compared to `http[s]://`.

**Comment by peff** [comment] 2017-02-22 18:51
@smarts Ah, thanks. Should be fixed as of #968, and now that these are redirects, I think engines like Google are smart enough to start sending people to the redirect destination.
