### ISSUE TITLE
Weird behavior of version toggle on doc pages

### ISSUE THREAD

**Issue by rybak** [git/git-scm.com#1041] opened 2017-10-10 09:39 UTC
Steps:

1. Opened https://git-scm.com/docs/git-cherry
2. Clicked version toggle and chose 1.8.5.2
3. Got following result:

![git_-_git-cherry_documentation_-_google_chrome_2017-10-10t12-33-39](https://user-images.githubusercontent.com/624072/31379789-fdbd1e8c-adb7-11e7-92c8-d500818258c8.png)

**Comment by jnavila** [comment] 2017-10-10 10:00
It seems only the preceding version can not be reached. Weird indeed.

**Comment by pedrorijo91** [comment] 2017-10-10 10:06
do we have any logs on heroku that can help? some entry missing on the db maybe?

**Comment by peff** [comment] 2017-10-10 10:41
We don't keep heroku logs for any length of time (because the site generates on the order of about 1GB of logs per day). However, I did just do a `heroku log --tail` while visiting the site. There's not much of interest there.

Trying to replicate in my local dev environment, it seems fine.

I have often seen funniness in the version-picker, and suspected that the code is not robust in the face of re-importing old versions. I'm tempted to blow away the production database table for the manpages and just re-run `preindex` to rebuild the whole thing. We could probably also consider skipping over some old versions, as the version table for some commands is getting ridiculously long. That would require some filtering in the `index.rake` task, though (since it wants to add any new versions it can find).

**Comment by peff** [comment] 2017-10-10 11:02
> I'm tempted to blow away the production database table for the manpages and just re-run preindex to rebuild the whole thing. 

I'm doing this now. I don't see an easy way to do it atomically, so you may see some missing versions while the rebuild runs.

**Comment by jnavila** [comment] 2017-10-10 11:17
Lets :crossed_fingers: that my last changes didn't break anything.

**Comment by jnavila** [comment] 2017-10-10 11:51
Still strange how git 2.13.1 is cited, where as there didn't seem to have any change at that version:

```bash
$ git log --oneline Documentation/git-cherry.txt | cut -f 1 -d " " | xargs git describe --contains
v1.8.5.2~2^2
v1.8.5-rc0~86
v1.7.6.1~25^2
v1.7.5-rc0~81^2~2
v1.7.0-rc0~7^2~12
v1.6.2-rc0~169^2
v1.6.2-rc0~169^2~1
v1.6.0-rc1~89
v1.6.0-rc0~142
v1.6.0-rc0~165
v1.6.0-rc0~166
v1.5.6-rc2~4
v1.5.6-rc1~30
...
```

**Comment by peff** [comment] 2017-10-10 12:43
> Still strange how git 2.13.1 is cited, where as there didn't seem to have any change at that version

Yeah, that is strange. I wonder if it's related to how we decide that two pages are the "same". I don't think it uses the upstream Git SHA-1 (which would be wrong in the face of dependent includes that change), but rather takes a hash of the expanded contents. So any time we make a change to the import code but _don't_ re-import all of the historical tags, that may trigger a "change" between the two versions.

That could happen in this case either because we made a change around the v2.13.1 time-frame that got picked up when it was released. Or because I sometimes rebuild older versions to pick up fixes, but don't go all the way back to the beginning of history (because it's really expensive to do so via preindex).

**Comment by peff** [comment] 2017-10-10 15:33
So this is _sort of_ fixed. I re-imported all of the manpages, which made the confusing output go away. But now the `git cherry` page doesn't show _any_ old versions!

It turns out that this is caused by limiting done in the version-check: we only look back 100 tags, which goes to v2.0-ish, which is after the latest updates to that page. I've opened #1045 which fixes this, though I'm a little nervous that it could create performance problems.

Along the way I also noticed a recent bug in the `preindex` task: we were re-building tags we had already imported. It's _possible_ this was related to the funny output here, as we run `preindex` every night. So it would try reimporting from the beginning of time forward, and would probably run out of API limits sometime in the middle. So it's possible that this constant partial-reimporting ended up confusing things.
Anyway, that's dealt with in #1044.

**Comment by jnavila** [comment] 2017-10-10 15:56
The sha1 used to track change in pages is the one of the asciidoc with includes resolved. That means that each time we change the way the includes are resolved (such as the change concerning merge and diff tools), the import script will detect a fake version change.

**Comment by crea1** [comment] 2017-10-16 05:46
I don't know if this is related to this issue, but https://git-scm.com/docs/git-config, seems to show an old version of the documentation. If you compare with https://www.kernel.org/pub/software/scm/git/docs/git-config.html, you'll see things are missing. Was looking for the section with conditional includes (released in 2.13), which I'm sure was there before.

**Comment by jnavila** [comment] 2017-10-16 06:58
https://git-scm.com/docs/git-config/2.9.1 gives a HTTP 500.

**Comment by peff** [comment] 2017-10-16 16:40
@jnavila That page seems fine now. I suspect that may have been related to the timeouts we were having with #1045 (which has since been reverted).

**Comment by peff** [comment] 2017-10-16 16:44
@crea1 Yeah, the content for the `git-config` page is definitely not up to date. One thing to note is that the documentation in question is actually in `config.txt`, which is _included_ by `git-config.txt`. And while the include changed recently, the parent `git-config.txt` file hasn't changed since v2.9.3.

So I suspect the includes are fooling the same-version check. I think we store a sha1 of the pre-rendered content in the database as a unique key to detect changes. That should definitely be on the expanded contents. Which, looking at https://github.com/git/git-scm.com/blob/928cf3c3026cc56bf9802b0995e0942ee12b4b48/lib/tasks/index.rake#L119, it _seems_ to be. But maybe I'm missing something.

**Comment by peff** [comment] 2017-10-16 16:51
Hmph. When I rebuild `v2.9.3`, then `v2.10.0`, then `v2.14.2` locally on a fresh database, everything looks fine. So I'm totally confused about how this corrupted state comes about.

**Comment by jnavila** [comment] 2017-10-16 18:29
@peff you're right  `asciidoc.source` is `content` which has  been expanded. So it should be correct wrt to includes expansion.

**Comment by jnavila** [comment] 2017-10-16 18:35
But for me, git-config still isn't up to date though, conditional includes are missing.

**Comment by peff** [comment] 2017-10-16 18:56
> But for me, git-config still isn't up to date though, conditional includes are missing.

I think it should be OK now, after doing a manual `RERUN=1 REBUILD_DOC=v2.14.2 rake preindex`. I'm still utterly confused about why it was broken in the first place. I'd _suspect_ that it's related to the fact that when I did the full rebuild last week I built v2.14.2 first (so that people had the latest docs) and then back-filled. But I can't seem to replicate that in my local environment.

**Comment by peff** [comment] 2017-10-16 18:58
> I think it should be OK now

Note that it's still stale in the cloudflare cache. I'll purge that in a moment. But in general for things like this, checking https://git-scm.herokuapp.com/ is a good cross-check to make sure we're not hitting any caching there (I also flushed the redis cache, which can contribute to out-of-date views).

**Comment by jnavila** [comment] 2017-10-17 15:25
>I think it should be OK now, after doing a manual RERUN=1 REBUILD_DOC=v2.14.2 rake preindex.


if the order of feeding the versions into the database matters, then

https://github.com/git/git-scm.com/blob/master/lib/tasks/index.rake#L11

might be the culprit. Obviously, the versions are ordered alphatically, which would place v2.9.x versions after v2.14.x.

I've seen a code snippet to order the versions correctly and I can apply it here if it makes sense.

**Comment by peff** [comment] 2017-10-17 16:59
@jnavila Good thinking. I noticed that out-of-order bit during the rebuild (since the full rebuild ended on v2.9.x, not v2.14.2 as I expected) but for some reason didn't put two and two together. It does seem like a possible culprit (though I haven't managed to replicate the out-of-order problem in my local environment).

At any rate, sorting by version seems like a sane thing to be doing anyway.

(Also, while I'm thinking of it: one other thing I noticed during the rebuild is that `REBUILD_DOC=v2.14.2` is no longer sufficient to trigger a rebuild. You have to pass `RERUN=1`, too. I think this dates to the recent refactoring of the index tasks. Not a big deal, but it confused me for a moment).

**Comment by jnavila** [comment] 2017-10-17 19:05
Before the refactoring, the `RERUN` env variable was only checked in the `preindex` target. With the refactoring, I had commented it in the main function, but then all the versions were rebuilt by the crontab script on the server. So you uncommented it to calm down everything; the behaviors of `preindex` and `local_index` are now similar.

**Comment by jnavila** [comment] 2017-11-10 18:01
Everything is ok, now.

**Closed by jnavila** 2017-11-10 18:01 UTC
