### ISSUE TITLE
Cannot access Mac or Windows installers.

### ISSUE THREAD

**Issue by asmyers** [git/git-scm.com#1042] opened 2017-10-10 13:53 UTC
https://git-scm.com/download/mac and https://git-scm.com/download/win seem to redirect back to https://git-scm.com/download making it impossible to access installers for either platform.

```
╰─➤  curl https://git-scm.com/download/mac                                                                                                                                                             1 ↵
<html><body>You are being <a href="https://git-scm.com/downloads">redirected</a>.</body></html>
```

```
wget --no-check-certificate https://git-scm.com/download/mac                                                                                                                                      5 ↵
--2017-10-10 09:51:58--  https://git-scm.com/download/mac
Resolving git-scm.com... 2400:cb00:2048:1::6814:262b, 2400:cb00:2048:1::6814:252b, 104.20.38.43, ...
Connecting to git-scm.com|2400:cb00:2048:1::6814:262b|:443... connected.
WARNING: cannot verify git-scm.com's certificate, issued by ‘CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 302 Found
Location: https://git-scm.com/downloads [following]
--2017-10-10 09:51:58--  https://git-scm.com/downloads
Reusing existing connection to [git-scm.com]:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘mac’
```

**Comment by pedrorijo91** [comment] 2017-10-10 14:02
can it be due to https://github.com/git/git-scm.com/pull/1038 @peff ?

**Comment by jzunigarce** [comment] 2017-10-10 14:04
:(

**Comment by pedrorijo91** [comment] 2017-10-10 14:07
in the meanwhile:

* mac download link: https://sourceforge.net/projects/git-osx-installer/files/git-2.14.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect
* windows 32 bits https://github.com/git-for-windows/git/releases/download/v2.14.2.windows.2/Git-2.14.2.2-32-bit.exe
* windows 64 bits https://github.com/git-for-windows/git/releases/download/v2.14.2.windows.2/Git-2.14.2.2-64-bit.exe

**Comment by jzunigarce** [comment] 2017-10-10 14:08
Thanks

**Comment by rwb27** [comment] 2017-10-10 14:18
Just in case it's not obvious, I have the same problem from Chrome and Firefox on Windows (10, 64-bit).  Thanks for the download links here!

**Comment by peff** [comment] 2017-10-10 14:39
Eep, this should be fixed now. The database schema for the downloads references the versions sucked in via the manpages (for no reason that I can discern), and so needed to be rebuilt when the manpage database was rebuilt.

**Comment by peff** [comment] 2017-10-10 14:53
Closing as this should be good now (I had some cache funniness with refreshing in firefox, but I've confirmed that both heroku and cloudflare have cleared caches, so anything leftover _should_ be client-side). Let me know if I'm wrong.

**Closed by peff** 2017-10-10 14:53 UTC

**Comment by JaviHG** [comment] 2017-10-11 07:19
The Windows links doesn't work...

**Comment by pedrorijo91** [comment] 2017-10-11 07:21
have you tried to clean the cache @JaviHG ? I just tried and it works. try in another browser or incognito mode please

**Comment by JaviHG** [comment] 2017-10-11 07:29
Ok, the problem was with the URL, I was using the next:
URL NOT working =====> https://github.com/git-for-windows/git/releases/download/v2.14.2.windows.2/Git-2.14.2.2-64-bit.exe

The next URL work perfectly
URL working =====> https://git-scm.com/download/win

**Comment by pedrorijo91** [comment] 2017-10-11 07:33
weird, all links are working for me

**Comment by JaviHG** [comment] 2017-10-11 07:33
Ok, now is working both URL. Sorry for the inconvenience....
