### ISSUE TITLE
">" shown as "&gt;" (html entity) for Git Book

### ISSUE THREAD

**Issue by MichaWiedenmann** [git/git-scm.com#606] opened 2015-10-14 08:15 UTC
On https://git-scm.com/book/en/v2/Git-Internals-The-Refspec the fetch example shows (note the mangled arrow: `"-&gt;"` in line 4):

    $ git fetch origin master:refs/remotes/origin/mymaster \
             topic:refs/remotes/origin/topic
    From git@github.com:schacon/simplegit
     ! [rejected]        master     -&gt; origin/mymaster  (non fast forward)
     * [new branch]      topic      -&gt; origin/topic

But the [source](https://raw.githubusercontent.com/progit/progit2/master/book/10-git-internals/sections/refspec.asc) correctly uses `">"`:

    [source,console]
    ----
    $ git fetch origin master:refs/remotes/origin/mymaster \
             topic:refs/remotes/origin/topic
    From git@github.com:schacon/simplegit
     ! [rejected]        master     -> origin/mymaster  (non fast forward)
     * [new branch]      topic      -> origin/topic
    ----

**Comment by KellyWay** [comment] 2015-11-02 14:36
I am seeing misrendered html entities everywhere

**Comment by ip** [comment] 2015-11-29 23:17
Confirm

**Comment by offece** [comment] 2015-11-29 23:23
Create New Page · carlosgs/Cyclone-PCB-Factory

**Comment by offece** [comment] 2015-11-29 23:24
https://github.com/git/git-scm.com/issues/606#thread-subscription-status

**Comment by tremby** [comment] 2016-04-29 09:41
More cases at https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server

**Comment by peff** [comment] 2016-05-03 02:51
Closing as a duplicate of #753 (even though this is older, there are more details and links there). Thanks.

**Closed by peff** 2016-05-03 02:51 UTC
