### ISSUE TITLE
note bad style

### ISSUE THREAD

**Issue by Alexnder** [git/git-scm.com#592] opened 2015-09-17 10:10 UTC
https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9F%D0%BE%D0%B4%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8#id-RVNYFJ
![image 1](https://cloud.githubusercontent.com/assets/1038313/9930578/5dd2432e-5d3d-11e5-97d6-be0a38c60fbe.png)

**Comment by sxlijin** [comment] 2017-02-07 17:14
Hey, is this still an issue? I don't see it in the linked page anymore.

**Comment by peff** [comment] 2017-02-07 22:22
I thnk there were some similar reports, and I _think_ it has to do with line-spacing issues. It looks fine in my browser, though. I'm not sure if better CSS fixed it, it was a browser bug, or the issue is still lurking out there for some browsers. Will close this (and similar ones) for now. Re-open if it's still happening.

**Closed by peff** 2017-02-07 22:22 UTC
