### ISSUE TITLE
> encoded in "What now"

### ISSUE THREAD

**Issue by janekdb** [git/git-scm.com#742] opened 2016-04-14 11:51 UTC
https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging

Is: What now&gt;
Should be: What now>

**Comment by orens** [comment] 2016-04-18 15:03
Seems like this is a problem throughout the book. Every `<`, `>` is replaced with `&lt;`, `&gt;`
I randomly selected a page: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell, and right after Figure 3-5 there is an output sample with `->` written as `-&gt;`

BTW, seems like that's what the op intended to write, only he didn't escape it properly :)

**Comment by ip** [comment] 2016-04-26 07:43
Why on earth he still didn't fix it. I read the site about a year ago and same crap.

**Comment by peff** [comment] 2016-05-03 02:49
Closing as a duplicate of #753 (even though this is older, there are more details and links there). Thanks.

**Closed by peff** 2016-05-03 02:49 UTC
