### ISSUE TITLE
Broken link to Git credentials API docs

### ISSUE THREAD

**Issue by jasonhall-at-google** [git/git-scm.com#512] opened 2015-02-26 15:19 UTC
At the bottom of http://git-scm.com/docs/gitcredentials:

> CUSTOM HELPERS
> You can write your own custom helpers to interface with any system in which you keep credentials. See the documentation for Git’s [credentials API](http://git-scm.com/docs/technical/api-credentials.html) for details.

The link points to http://git-scm.com/docs/technical/api-credentials.html which redirects to the much less helpful http://git-scm.com/docs landing page.

The same issue is also present on http://git-scm.com/docs/git-credential

**Comment by Sicaine** [comment] 2017-02-07 21:19
FYI: I figured out where it should point: https://www.kernel.org/pub/software/scm/git/docs/technical/api-credentials.html

I haven't figured out yet how to fix it :-| but it might be even a bigger issue if those types of links are not replaced properly.

Perhaps i will find time on the weekend or someone else.

**Comment by peff** [comment] 2017-02-07 21:39
The issue is that the git-scm page does not pull in `Documentation/technical` at all. It would probably be reasonable to import them, but not link directly from the main index page (so as not to clutter it). It would need some hacking of the [preindex rake task](https://github.com/git/git-scm.com/blob/master/lib/tasks/index.rake).

I'm not sure how much work that would be, but it probably makes sense to hold off until we see what's happening with #942, as the whole import process will likely need re-written.

**Comment by sxlijin** [comment] 2017-09-27 04:14
Closing since #994 describes this better.

**Closed by sxlijin** 2017-09-27 04:14 UTC
