### ISSUE TITLE
Unrendered html entity codes appear in page content 

### ISSUE THREAD

**Issue by davesque** [git/git-scm.com#618] opened 2015-11-05 18:48 UTC
## Steps to reproduce

1. Navigate to http://git-scm.com/book/en/v2/Git-Internals-Git-Objects

## Expected behavior

No unrendered entity codes should appear in page content.

## Actual behavior

Unrendered entity codes ("\&gt;", "\&lt;", etc.) appear in page content (code snippets, in particular).

![git git objects](https://cloud.githubusercontent.com/assets/791437/10978244/042abd50-83b3-11e5-99ff-d6d7c30a1a1f.png)

**Comment by eesel** [comment] 2015-11-16 15:14
It's the same with 
http://www.git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server

![unrendered_html_entity_codes](https://cloud.githubusercontent.com/assets/6968278/11185429/06c54814-8c7d-11e5-80bc-721b77507fcd.png)

**Comment by jeremen** [comment] 2015-12-04 20:08
Also the same with https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by peff** [comment] 2016-05-03 02:51
Closing as a duplicate of #753 (even though this is older, there are more details and links there). Thanks.

**Closed by peff** 2016-05-03 02:51 UTC
